# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-GNIS
version:      0.01
version_from: GNIS.pm
installdirs:  site
requires:
    Geo::TigerLine:                0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
